--- 
title: 'Research Design: Declare, Diagnose, Redesign'
author: "Graeme Blair, Alexander Coppock, and Macartan Humphreys"
site: bookdown::bookdown_site
knit: "bookdown::render_book"
output: pdf_document
bibliography:
- bib/book.bib
- bib/packages.bib
biblio-style: apsr
link-citations: yes
description: describe the book
header-includes:
- \usepackage{amsmath, amssymb, amstext, bbm, array}
- \newcommand\E{\mathbb{E}}
- \newcommand\V{\mathbb{V}}
- \newcommand\cov{\mathrm{cov}}
keep_tex: yes
documentclass: book
---


```{r book-setup, echo = FALSE, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, cache = FALSE, out.width = "100%", dev = "svg")
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file()) # files are all relative to RStudio project home
do_bookdown <- TRUE
# show_flags  is define in before_chapter_script
```

```{r, eval = !exists("do_bookdown"), echo = FALSE, include = FALSE, purl = FALSE}
# load common packages, set ggplot ddtheme, etc.
source("scripts/before_chapter_script.R")
source("scripts/vayr.R")
source("scripts/flagit.R")
```

# Research Design: Declaration, Diagnose, Redesign {-}

```{r, fig.width = 7, fig.height = 2.7, echo = FALSE, warning = FALSE}
dag <-
  dagify(aw ~ w + I,
         m ~ M,
         am ~ m + I,
         d ~ D + w,
         ad ~ A + d,
         w ~ W)

dag_base <- tidy_dagitty(dag) %>%
  select(name, direction, to, circular) %>%
  as_tibble

nodes_df <-
  tibble(
    name = c("M", "I", "D", "A", 
             "m", "am", "aw", "d", 
             "ad", "w", "W"),
    label = c("M", "I", "D", "A", "m", "a<sup>m</sup>", "a<sup>w</sup>", "d", "a<sup>d</sup>", "w", "W"),
    long_label = c("Theoretical<br>causal model", "Inquiry<br>", "Data<br>strategy", "Answer<br>strategy", "Model<br>draw", "Theoretical<br>answer", "True<br>answer", "Realized<br>data", "Empirical<br>answer", "Real<br>world", "True causal<br>model"),
    lbl_direction = c("N", "N", "N", "N", "S", "S", "S", "S", "S", "S", "N"),
    x = c(1.5, 3.5, 11.5, 13.5, 
          1.5, 3.5, 8.5, 11.5, 
          13.5, 6.5, 6.5),
    y = c(3.5, 3.5, 3.5, 3.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 3.5)
  )

endnodes_df <-
  nodes_df %>%
  transmute(to = name, xend = x, yend = y)

gg_df <-
  dag_base %>%
  left_join(nodes_df, by = "name") %>%
  left_join(endnodes_df, by = "to")

gg_df <-
  gg_df %>%
  mutate(arced1 = (name == "w" & to == "d"),
         arced2 = (name == "I" & to == "aw")) %>%
  arrange(name)

# rect_df <-
#   tibble(
#     xmin = c(.4, 4.9),
#     xmax = c(2.6, 7.1),
#     ymin = c(1.15, 1.15),
#     ymax = c(3.85, 3.85)
#   )

rect_df <-
  tibble(
    xmin = c(0, 10),
    xmax = c(5, 15),
    ymin = c(0, 0),
    ymax = c(5, 5)
  )

g <-
  ggplot(data = filter(gg_df, !arced1 & !arced2), aes(
    x = x,
    y = y,
    xend = xend,
    yend = yend
  )) +
  geom_point(color = gray(.1), fill = NA, size = 14, stroke = 0.5, pch = 1) +
  geom_dag_edges(edge_width = 0.35) +
  geom_dag_edges_arc(data = filter(gg_df, arced1), curvature = -0.25, edge_width = 0.35) +
  geom_dag_edges_arc(data = filter(gg_df, arced2), curvature = .64, edge_width = 0.35) +
  geom_richtext(color = "black",
                aes(label = label, 
                    y = y + if_else(name %in% c("M", "I", "D", "A", "W"), -0.025, 0),),
                fill = NA,
                label.color = NA,
                label.padding = grid::unit(rep(0, 4), "pt"),
                size = 4) +
  # geom_richtext(aes(y = y + if_else(lbl_direction == "N", 0.75, -0.75),
  #       vjust = if_else(lbl_direction == "N", "bottom", "top"),
  #       label = long_label),
  #   color = gray(0.5),
  #   fill = NA,
  #   label.color = NA,
  #   label.padding = grid::unit(rep(0, 4), "pt"),
  #   size = 3) +
  geom_rect(data = rect_df, aes(x = NULL, y = NULL, 
                                xend = NULL, yend = NULL,
                                xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            alpha = 0.15) +
  # annotate("text", x = 2.5, y = 5.35, label = "Theory") +
  # annotate("text", x = 12.5, y = 5.35, label = "Empirics") +
  # annotate("text", x = 7.5, y = 5.35, label = "Reality") +
  coord_fixed(clip = "off") + 
  theme_dag()
g
```

## Graeme Blair, Alexander Coppock, and Macartan Humphreys {-}

### Draft manuscript under advance contract, Princeton University Press  {-}


<!-- mathabx -->
