---
title: "zosidfjoasidfjosdaijfasodifjasodifjasodifjaosdifjaosdifjaosdifjasdoifjasdofijoasdifjoasdijfoasidjfaoijsdf"
author: "Alex Coppock"
date: "8/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DeclareDesign)
library(dagitty)
library(ggdag)
library(dddag)
library(ggtext)
source("_scratch/make_ggdd_df.R")
```


# visual 

```{r}
nodes <-
  tibble(
    name = c("Y_star", "Y_1", "Y_2", "Y_3", "Y_idx"),
    label = c("Y^*", "Y<sup>1</sup>", "Y<sup>2</sup>", "Y<sup>3</sup>", "Index"),
    annotation = c(
      "**Latent outcome**<br>unmeasurable",
      "**Measured outcome**",
      "",
      "",
      "**Constructed index**"),
    x = c(-50, 0, 0, 0, 50),
    y = c(0, 25, 0, -25, 0),
    text_x = x,
    text_y = c(25, 50, 0, -25, 25),
  )
ggdd_df <- tibble(
  name = c("Y", "Z", "S", "M"),
  label = name,
  direction = NA,
  to = NA_integer_,
  circular = FALSE,
  data_strategy = c("unmanipulated", "assignment", "sampling", "measurement"),
  x = c(-100, -50, 0, 50),
  y = rep(0, 4),
  xend = NA_real_,
  yend = NA_real_,
  annotation = c("**unmanipulated**", "**assignment**", "**sampling**", "**measurement**"),
  text_x = x,
  text_y = y + 50,
  shape_y = if_else(data_strategy == "sampling", y + 6, y)
  # shape_size = case_when(
  #   data_strategy == "assignment" ~ 50, data_strategy == "sampling" ~ 50, 
  #   data_strategy == "measurement" ~ 50, data_strategy == "unmanipulated" ~ 50
  # )
)

base_dag_plot %+% ggdd_df
```

# latent outcomes

```{r}
 ## design declaration
```

```{r, echo = FALSE}
design <- 
  declare_population(N = 100, Y_star = rnorm(N)) +
  declare_estimand(Y_bar = mean(Y_star)) + 
  declare_measurement(Y_1 = 0.1 * Y_star + rnorm(N, sd = 0.25),
                      Y_2 = Y_star + rnorm(N, sd = 0.25),
                      Y_3 = 1 + 0.5 * Y_star + rnorm(N, sd = 0.25),
                      Y_idx = (Y_1 + Y_2 + Y_3) / 3) + 
  declare_estimator(Y_idx ~ 1, model = lm_robust, estimand = "Y_bar")

dag <- dagify(Y_1 ~ Y_star, Y_2 ~ Y_star, Y_3 ~ Y_star, Y_idx ~ Y_1 + Y_2 + Y_3)
nodes <- get_design_nodes(design)

nodes <-
  tibble(
    name = c("Y_star", "Y_1", "Y_2", "Y_3", "Y_idx"),
    label = c("Y^*", "Y<sup>1</sup>", "Y<sup>2</sup>", "Y<sup>3</sup>", "Index"),
    annotation = c(
      "**Latent outcome**<br>unmeasurable",
      "**Measured outcome**",
      "",
      "",
      "**Constructed index**"),
    x = c(-50, 0, 0, 0, 50),
    y = c(0, 25, 0, -25, 0),
    text_x = x,
    text_y = c(25, 50, 0, -25, 25),
  )
ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# mrp


```{r}
fixed_population <- declare_population(N = 500, 
                                       X = sample(c("A", "B", "C"), N, replace = TRUE),
                                       Y = sample(1:7, N, replace = TRUE))()

design <- 
  declare_population(data = fixed_population) + 
  declare_estimand(Ybar = mean(Y)) + 
  declare_sampling(strata_prob = c(0.2, 0.1, 0.3), strata = X) + 
  declare_step(B_demeaned = (X == "B") - mean(X == "B"),
               C_demeaned = (X == "C") - mean(X == "C"), mutate) + 
  declare_estimator(Y ~ B_demeaned + C_demeaned, term = "(Intercept)", model = lm_robust, estimand = "Ybar")

dag <- dagify(Y ~ S + X,
              S ~ X)
nodes <-
  tibble(
    name = c("X", "Y", "S"),
    label = c("X", "Y", "S"),
    annotation = c(
      "**Strata**<br>changes sampling probabilites",
      "**Outcome**<br>measured only for sampled units",
      "**Sampling indicator**<br>randomly set by designer"),
    x = c(-100, 100, -100),
    y = c(100, -100, -100),
    text_x = x,
    nudge_y = c(50, -50, -50),
    text_y = y + nudge_y
  )

ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# stepped wedge

```{r}

design <- 
  declare_population(
    unit = add_level(N = 8, X = rnorm(N)),
    period = add_level(N = 3, time = as.numeric(period), nest = FALSE),
    obs = cross_levels(by = join(unit, period), U = rnorm(N))
  ) + 
  declare_potential_outcomes(Y ~ X + U + Z * time) +
  declare_assignment(clusters = unit, conditions = 1:4, assignment_variable = "wave") + 
  declare_assignment(Z = as.numeric(time >= wave), ipw = 1 / (Z * 2/8 + (1 - Z) * (1 - 2/8)), handler = fabricate) + 
  declare_reveal(Y, Z) + 
  declare_estimand(ATE = mean(Y_Z_1 - Y_Z_0)) + 
  declare_estimator(Y ~ Z, model = lm_robust, estimand = "ATE", label = "1: Wave 2 only", subset = period == 2) +
  declare_estimator(Y ~ Z, model = lm_robust, estimand = "ATE", label = "2: Weighted, clustered SW", weights = ipw, clusters = unit) +
  declare_estimator(Y ~ Z, model = lm_robust, estimand = "ATE", label = "3: Unweighted, unclustered SW") 

dag <- dagify(Y ~ Z + X + U + time,
              Z ~ time)

nodes <-
  tibble(
    name = c("X", "U", "time", "Z", "Y"),
    label = c("X", "U", "T", "Z", "Y"),
    annotation = c(
      "**Unknown heterogeneity**<br>Unit effects",
      "**Unknown heterogeneity**<br>",
      "**Time period**<br>",
      "**Treatment assignment**<br>",
      "**Outcome variable**<br>"
    ),
    x = c(100, -100, -100, -10, 100),
    y = c(-100, 100, -100, 0, 0), 
    text_x = x,
    nudge_y = c(-50, 50, -50, 20, 50),
    text_y = y + nudge_y
  )

ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# saturation


```{r}

design <- 
  declare_population(
    group = add_level(N = 10, X = rnorm(N)),
    unit = add_level(N = 100, U = rnorm(N))
  ) +
  declare_assignment(clusters = group, conditions = c("low", "high"), assignment_variable = S) +
  declare_step(S_prob = case_when(S == "low" ~ 0.25, S == "high" ~ 0.75), mutate) +
  declare_assignment(blocks = group, prob_unit = S_prob) + 
  declare_potential_outcomes(
    Y ~ Z + (S == "high") + Z*(S == "high") + X + U,
    conditions = list(Z = c(0, 1), S = c("low", "high"))) +
  declare_estimand(ATE_saturation = mean(Y_Z_0_S_high - Y_Z_0_S_low),
                   ate_no_spill = mean(Y_Z_1_S_low - Y_Z_0_S_low)) +
  declare_reveal(Y, c(Z, S)) +
  declare_estimator(Y ~ Z + S, model = lm_robust, term = c("Z", "Shigh"), estimand = c("ATE_saturation", "ate_no_spill"), label = "main effect")

dag <- dagify(Y ~ Z + S + U + X,
              Z ~ S)

nodes <-
  tibble(
    name = c("X", "U", "S", "Z", "Y"),
    label = c("X", "U", "S", "Z", "Y"),
    annotation = c(
      "**Unknown heterogeneity**<br>Unit effects",
      "**Unknown heterogeneity**",
      "**Treatment assignment 1**<br>Saturation level",
      "**Treatment assignment 2**<br>Individual assignment",
      "**Outcome variable**"
    ),
    x = c(10, 10, -25, -25, 50),
    y = c(-50, 50, 25, -25, 0), 
    text_x = x,
    nudge_y = c(-10, 10, 18, -18, 18),
    text_y = y + nudge_y
  )

ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# encouragement


```{r}
 
direct_effect_of_encouragement <- 0.0
proportion_defiers <- 0.0


design <-
  declare_population(
    N = 100,
    type = sample(
      x = c("Always-Taker", "Never-Taker", "Complier", "Defier"),
      prob = c(0.1, 0.1, 0.8, 0.0),
      size = N, replace = TRUE
    ),
    U = rnorm(N)
  ) +
  declare_potential_outcomes(
    D ~ case_when(
      Z == 1 & type %in% c("Always-Taker", "Complier") ~ 1,
      Z == 1 & type %in% c("Never-Taker", "Defier") ~ 0,
      Z == 0 & type %in% c("Never-Taker", "Complier") ~ 0,
      Z == 0 & type %in% c("Always-Taker", "Defier") ~ 1
    )
  ) +
  declare_potential_outcomes(
    Y ~ 0.5 * (type == "Complier") * D +
      0.25 * (type == "Always-Taker") * D +
      0.75 * (type == "Defier") * D +
      # Building in NO excludability violation
      0 * Z + U,
    assignment_variables = c("D", "Z")
  ) +
  declare_estimand(CACE = mean(Y_D_1_Z_1 - Y_D_0_Z_0),
                   subset = type == "Complier") +
  declare_assignment(prob = 0.5) +
  declare_reveal(D, assignment_variable = "Z") +
  declare_reveal(Y, assignment_variables = c("D", "Z")) +
  declare_estimator(Y ~ D | Z, model = iv_robust, estimand = "CACE")

dag <- dagify(Y ~ D + type + U,
              D ~ Z + type + U,
              type ~ U)

nodes <-
  tibble(
    name = c("Z", "D", "U", "Y", "type"),
    label = c("Z", "D", "U", "Y", "C"),
    annotation = c(
      "**Random assignment**",
      "**Treatment received**",
      "**Unknown heterogeneity**",
      "**Outcome**",
      "**Principal stratum**<br>Compliance type"
    ),
    x = c(-50,0,-25, 50, 25),
    y = c(0, 0, 50, 0, 50),
    text_x = x,
    nudge_y = c(18, -18, 18, -18, 18),
    text_y = y + nudge_y
  )

ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# factorial


```{r}
design <-
  declare_population(N = 1000, U = runif(N)) +
  declare_potential_outcomes(
    # Difference 1: 0.6 - 0.4 = 0.2
    Y_Z_1 = if_else(0.4 < U, 1, 0),
    Y_Z_2 = if_else(0.6 < U, 1, 0),
    # Difference 2: 0.6 - 0.5 = 0.1
    Y_Z_3 = if_else(0.5 < U, 1, 0),
    Y_Z_4 = if_else(0.6 < U, 1, 0)
    # Difference-in-differences (also called the interaction effect): 0.2 - 0.1 = 0.1
  ) +
  declare_assignment(conditions = 1:4) +
  declare_assignment(Z1 = as.numeric(Z %in% c(2, 4)),
                     Z2 = as.numeric(Z %in% c(3, 4)),
                     handler = mutate) +
  declare_reveal(Y, Z) +
  declare_estimator(Y ~ Z1 + Z2 + Z1 * Z2,
                    model = lm_robust,
                    term = "Z1:Z2")

# diagnosis <-
#   design %>%
#   redesign(N = c(500, 1000, 3000, 5000)) %>%
#   diagnose_design(sims = 500, bootstrap_sims = FALSE)
# 
# diagnosis %>%
#   get_diagnosands() %>%
#   ggplot(aes(N, power)) +
#   geom_line() +
#   geom_hline(yintercept = 0.8, linetype = "dashed") +
#   theme_bw() +
#   ggtitle("Power for the interaction term in a 2x2 factorial experiment",
#           "When the difference in the effect of factor 1 depending on the level of factor 2 is 10pp")

dag <-
  dagify(Y ~ Z1 + Z2 + U)

nodes <-
  tibble(
    name = c("Y", "Z1", "Z2", "U"),
    label = c("Y", "Z1", "Z2", "U"),
    annotation = c(
      "**Outcome**<br>",
      "**Random assignment 1**<br> Factor number 1",
      "**Random assignment 2**<br> Factor number 2",
      "**Unknown heterogeneity**"),
    x = c(0, -50, -50, 50),
    y = c(0, -50, 50, 0), 
    text_x = x,
    nudge_y = c(18, 18, 18, 18),
    text_y = y + nudge_y
  )

ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# two arm trial


```{r}

design <-
  declare_population(N = 100, U = rnorm(N)) +
  declare_potential_outcomes(Y ~ Z + U) +
  declare_estimand(ATE = mean(Y_Z_1 - Y_Z_0)) +
  declare_assignment(prob = 0.5) +
  declare_estimator(Y ~ Z, estimand = "ATE")

# dagify(
#   Y ~ Z + U
# )

get_design_nodes(design)

dag <- get_dag(design)

# plot(design)
# plot(dag)

nodes <-
  tibble(
    name = c("Y", "Z", "U"),
    label = c("Y", "Z", "U"),
    annotation = c(
      "**Outcome**<br>",
      "**Random assignment**<br>",
      "**Unknown heterogeneity**"),
    x = c(25, -25, 25),
    y = c(-25, -25, 25), 
    text_x = x,
    nudge_y = c(-18, -18, 18),
    text_y = y + nudge_y
  )

ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# blocking


```{r}

design <-
  declare_population(N = 100,
                     X = rbinom(N, 1, 0.3),
                     U = rnorm(N)) +
  declare_potential_outcomes(Y ~ Z + X + U) +
  declare_estimand(ATE = mean(Y_Z_1 - Y_Z_0)) +
  declare_assignment(blocks = X, block_prob = c(0.1, 0.5)) +
  declare_estimator(Y ~ Z, estimand = "ATE", label = "Naive DIM") +
  declare_estimator(Y ~ Z,
                    blocks = X,
                    estimand = "ATE",
                    label = "Blocked DIM")

dag <- dagify(
  Y ~ Z + X + U,
  Z ~ X
)

get_design_nodes(design)

# dag <- get_dag(design)

# plot(design)
# plot(dag)

nodes <-
  tibble(
    name = c("Y", "Z", "U", "X"),
    label = c("Y", "Z", "U", "X"),
    annotation = c(
      "**Outcome**<br>",
      "**Random assignment**<br>",
      "**Unknown heterogeneity**",
      "**Covariate**<br>Used for blocking"),
    x = c(25, -25, 25, -25),
    y = c(-25, -25, 25, 25), 
    text_x = x,
    nudge_y = c(-18, -18, 18, 18),
    text_y = y + nudge_y
  )
ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# synth

```{r, echo=FALSE}

library(Synth)

synth_weights_tidy <- function(data, predictors, time.predictors.prior, dependent, unit.variable, time.variable, treatment.identifier, controls.identifier) {
  dataprep.out <- dataprep(
    foo = data,
    predictors = predictors,
    predictors.op = "mean",
    time.predictors.prior = time.predictors.prior,
    dependent = dependent,
    unit.variable = unit.variable,
    time.variable = time.variable,
    treatment.identifier = treatment.identifier,
    controls.identifier = controls.identifier, 
    time.optimize.ssr = time.predictors.prior,
    time.plot = time.predictors.prior)
  capture.output(fit <- synth(data.prep.obj = dataprep.out))
  tab <- synth.tab(dataprep.res = dataprep.out, synth.res = fit) 
  
  weights_df <- tab$tab.w %>% mutate(synth_weights = w.weights) %>% dplyr::select(synth_weights, !!unit.variable := unit.numbers)
  data %>%
    left_join(weights_df) %>%
    mutate(synth_weights = replace_na(synth_weights, 1))
}

```


```{r}

design <- 
  declare_population(
    unit = add_level(N = 10, units = 1:N, X = rnorm(N, sd = 0.5)),
    period = add_level(N = 3, time = 1:N, nest = FALSE),
    unit_period = cross_levels(by = join(unit, period), U = rnorm(N))
  ) + 
  declare_potential_outcomes(Y ~ X + 0.5 * as.numeric(period) + Z + U) + 
  declare_estimand(ATE = mean(Y_Z_1 - Y_Z_0), subset = period == 3) + 
  declare_step(handler = mutate, Z = unit == "01") + 
  declare_reveal(Y = if_else(Z == 0 | period < 3, Y_Z_0, Y_Z_1), handler = mutate) +
  declare_step(predictors = "X",
               time.predictors.prior = 1:2,
               dependent = "Y",
               unit.variable = "units",
               time.variable = "time",
               treatment.identifier = 1,
               controls.identifier = 2:10, 
               handler = synth_weights_tidy) +
  declare_estimator(Y ~ Z, subset = time >= 3, weights = synth_weights, model = lm_robust, label = "synth")



# Simulation --------------------------------------------------------------

# simulations <- simulate_design(design, sims = 100)
# ggplot(simulations, aes(estimate)) + geom_histogram()


# Synth plot --------------------------------------------------------------

# data <- draw_data(design)
# summary_df <- data %>%
#   group_by(Z, time) %>%
#   summarize(Y = weighted.mean(Y, w = synth_weights))
# ggplot(summary_df, aes(x = time, y = Y, color = Z)) +
#   geom_line(size = 2, alpha = 0.5) +
#   geom_line(data = data, aes(x = time, y = Y, group = units), color = "black", alpha = 0.3) +
#   geom_point(data = data, aes(x = time, y = Y, size = synth_weights^2), alpha = 0.3) +
#   geom_vline(xintercept = 2.5)

dag <- dagify(Y ~ X + period + Z + U,
              Z ~ X)

get_design_nodes(design)

nodes <-
  tibble(
    name = c("U", "X", "period", "Z", "Y"),
    label = c("U", "X", "T", "Z", "Y"),
    annotation = c(
      "**Unknown heterogeneity**",
      "**Unit effect**",
      "**Time period**",
      "**Treatment assignment**",
      "**Outcome variable**"
    ),
    x = c(50, -25, -25, 0, 50),
    y = c(-50, 50, -50, 0, 0), 
    text_x = x,
    nudge_y = c(-10, 10, -10, -18, 18),
    text_y = y + nudge_y
  )

ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# did


```{r}

design <- 
  declare_population(
    unit = add_level(N = 2, X = rnorm(N, sd = 0.5)),
    period = add_level(N = 2, nest = FALSE),
    unit_period = cross_levels(by = join(unit, period), U = rnorm(N, sd = 0.01))
  ) + 
  declare_potential_outcomes(Y ~ X + 0.5 * as.numeric(period) + Z + U) + 
  declare_estimand(ATE = mean(Y_Z_1 - Y_Z_0), subset = period == 2) + 
  declare_step(Z = X == max(X), handler = mutate) + 
  declare_reveal(Y = if_else(Z == 0 | period == 1, Y_Z_0, Y_Z_1), handler = mutate) +
  declare_estimator(Y ~ Z * period, model = lm_robust, se_type = "none")

dag <- dagify(Y ~ X + period + Z + U,
              Z ~ X)

nodes <-
  tibble(
    name = c("U", "X", "period", "Z", "Y"),
    label = c("U", "X", "T", "Z", "Y"),
    annotation = c(
      "**Unknown heterogeneity**",
      "**Unit effect**",
      "**Time period**",
      "**Treatment assignment**",
      "**Outcome variable**"
    ),
    x = c(50, -25, -25, 0, 50),
    y = c(-50, 50, -50, 0, 0), 
    text_x = x,
    nudge_y = c(-10, 10, -10, -18, 18),
    text_y = y + nudge_y
  )
## Node placement

ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# behavioral games


```{r}
 
design <-
  declare_population(
    games = add_level(N = 100),
    players = add_level(
      N = 2,
      prosociality = runif(N),
      fairness = prosociality,
      cutoff = pmax(prosociality - 0.25, 0)
    )
  ) +
  declare_estimand(mean_fairness = mean(fairness),
                   mean_cutoff = mean(cutoff)) +
  declare_assignment(blocks = games, conditions = c("proposer", "responder"), assignment_variable = "role") + 
  declare_step(id_cols = games, names_from = role, values_from = c(prosociality, fairness, cutoff), handler = pivot_wider) + 
  declare_measurement(proposal = fairness_proposer * 0.5, 
                      response = if_else(proposal >= cutoff_responder, 1, 0)) + 
  declare_estimator(proposal ~ 1,
                    model = lm_robust,
                    estimand = "mean_fairness",
                    label = "mean_fairness") +
  declare_estimator(response ~ 1,
                    model = lm_robust,
                    estimand = "mean_cutoff",
                    label = "mean_cutoff")

dag <- dagify(fairness ~ prosociality,
              cutoff ~ prosociality,
              proposal ~ fairness + role,
              response ~ proposal + cutoff + role)

# plot(dag)           
              
# get_design_nodes(design)

nodes <-
  tibble(
    name = c("prosociality", "cutoff", "fairness", "role", "proposal", "response"),
    label = c("Y<sup>1*</sup>", "Y<sup>3*</sup>", "Y<sup>2*</sup>", "Z", "Y<sup>2</sup>", "Y<sup>1</sup>"),
    annotation = c(
      "**Latent trait**<br>Prosociality",
      "**Latent trait**<br>Cutoff",
      "**Latent trait**<br>Fairness",
      "**Random assignment**<br>Role",
      "**Outcome 1**<br>Proposal",
      "**Outcome 2**<br>Response"
    ),
    
    x = c(-100, -50,-50, -25, 25, 25) + 25,
    y = c(0, -50, 50, 0, 50, -50),
    text_x = x,
    nudge_y = c(18, 18, 18, 18, 18, -18),
    text_y = y + nudge_y
  )


ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# conjoint


```{r}
# applies the function to each pair
Y_function <- function(data) {
  data %>%
    group_by(pair) %>%
    mutate(Y = if_else(E == max(E), 1, 0)) %>%
    ungroup
}
design <- 
  declare_population(
    subject = add_level(N = 500),
    pair = add_level(N = 4),
    candidate = add_level(N = 2, U = runif(N))
  ) +
  declare_assignment(assignment_variable = "A1") +
  declare_assignment(assignment_variable = "A2", 
                     conditions = c("young", "middle", "old")) +
  declare_assignment(assignment_variable = "A3")  +
  declare_step(
    E = 
      0.05 * A1 + 
      0.04 * (A2 == "middle") + 
      0.08 * (A2 == "old") + 
      0.02 * A3 + U,
    handler = fabricate) +
  declare_measurement(handler = Y_function) +
  declare_estimator(Y ~ A1 + A2 + A3,
                    model = lm_robust, term = TRUE)

dag <- dagify(Y ~ E,
              E ~ U + A1 + A2 + A3)

nodes <-
  tibble(
    name = c("A1", "A2", "A3", "E", "Y", "U"),
    label = c("A1", "A2", "A3", "E", "Y", "U"),
    annotation = c("**Random assignment**<br>Coethnicity attribute",
                   "**Random assignment**<br>Age attribute",
                   "**Random assignment**<br>Gender attribute",
                   "**Latent outcome**<br>Candidate evaluation",
                   "**Measured outcome**<br>Candidate choice",
                   "**Unknown heterogeneity**"),
    x = c(-50, -50, -50, 0, 50, 0),
    y = c(50, 0, -50, 0, 0, 50),
    text_x = x,
    nudge_y = c(18, 18, 18, -18, 18, 18),
    text_y = y + nudge_y
  )

ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# SOO


```{r}
 
design <-
  declare_population(N = 100, 
                     X_1 = rnorm(N),
                     X_2 = rnorm(N),
                     Z = if_else(X_1 + X_2 > 0, 1, 0),
                     U = rnorm(N)) +
  declare_potential_outcomes(Y ~ Z + X_1 + X_2 + U) +
  declare_estimand(ATE = mean(Y_Z_1 - Y_Z_0)) +
  declare_reveal() +
  declare_estimator(Y ~ X_1 + X_2, model = lm_robust, estimand = "LATE") 

dag <- dagify(Y ~ X_1 + X_2 + Z + U,
              Z ~ X_1 + X_2)

nodes <-
  tibble(
    name = c("X_1", "X_2", "U", "Z", "Y"),
    label = c("X<sup>1</sup>", "X<sup>2</sup>", "U", "Z", "Y"),
    annotation = c(
      "**Exogenous variable 1**",
      "**Exogenous variable 2**",
      "**Unknown heterogeneity**",
      "**Treatment assignment**",
      "**Outcome variable**"
    ),
    x = c(-75, -75, 25, -25, 25),
    y = c(25, -25, 50, 0, 0), 
    text_x = x,
    nudge_y = c(18, -18, 18, -20, -18),
    text_y = y + nudge_y
  )


ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# IV


```{r}
 
design <-
  declare_population(N = 100, u = rnorm(N)) +
  declare_potential_outcomes(D ~ if_else(Z + u > 0, 1, 0), assignment_variables = Z) + 
  declare_potential_outcomes(Y ~ 0.1 * D + 0.25 + u, assignment_variables = D) +
  declare_estimand(late = mean(Y_D_1[D_Z_1 == 1 & D_Z_0 == 0] - Y_D_0[D_Z_1 == 1 & D_Z_0 == 0])) +
  declare_assignment(prob = 0.5) +
  declare_reveal(D, Z) + 
  declare_reveal(Y, D) + 
  declare_estimator(Y ~ D | Z, model = iv_robust, estimand = "LATE") 

dag <- dagify(Y ~ D + u,
              D ~ Z + u)

nodes <-
  tibble(
    name = c("Z", "D", "u", "Y"),
    label = c("Z", "D", "u", "Y"),
    annotation = c(
      "**Exogenous variable**<br>Instrument",
      "**Endogenous variable**",
      "**Unknown heterogeneity**",
      "**Outcome**"
    ),
    x = c(-75,-25,0, 25),
    y = c(0, 0, 50, 0),
    text_x = x,
    nudge_y = c(25, -18, 18, -18),
    text_y = y + nudge_y
  )

ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# RDD


```{r}

cutoff <- 0.5
control <- function(X) {
  as.vector(poly(X, 4, raw = TRUE) %*% c(.7, -.8, .5, 1))}
treatment <- function(X) {
  as.vector(poly(X, 4, raw = TRUE) %*% c(0, -1.5, .5, .8)) + .15}

design <-
  declare_population(
    N = 1000,
    U = rnorm(N, 0, 0.1),
    X = runif(N, 0, 1) + U - cutoff,
    Z = 1 * (X > 0)
  ) +
  declare_potential_outcomes(Y ~ Z * treatment(X) + (1 - Z) * control(X) + U) +
  declare_estimand(LATE = treatment(0) - control(0)) +
  declare_reveal(Y, Z) +
  declare_estimator(Y ~ poly(X, 4) * Z, model = lm_robust, estimand = "LATE")

dag <- dagify(Y ~ Z + X + U,
              Z ~ X,
              X ~ U)

nodes <-
  tibble(
    name = c("U", "X", "Z", "Y"),
    label = c("U", "X", "Z", "Y"),
    annotation = c(
      "**Unknown heterogeneity**",
      "**Exogenous variable**",
      "**Treatment assignment**",
      "**Outcome variable**"
    ),
    x = c(-25, -75, -25, 25),
    y = c(25, 0, -25, 0), 
    text_x = x,
    nudge_y = c(18, -18, -18, -18),
    text_y = y + nudge_y
  )

ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# list experiment


```{r}
 
design <-
  declare_population(
    N = 100,
    Y_star = rbinom(N, size = 1, prob = 0.3),
    S = case_when(Y_star == 0 ~ 0L,
                  Y_star == 1 ~ rbinom(N, size = 1, prob = 0.2)),
    X = rbinom(N, size = 3, prob = 0.5)
  ) +
  declare_estimand(proportion = mean(Y_star)) +
  declare_measurement(Y_direct = Y_star - S) +
  declare_potential_outcomes(Y_list ~ Y_star * Z + X) +
  declare_assignment(prob = 0.5) +
  declare_estimator(Y_direct ~ 1,
                    model = lm_robust,
                    estimand = "proportion",
                    label = "direct") +
  declare_estimator(Y_list ~ Z, estimand = "proportion", label = "list")

dag <- dagify(Y_direct ~ Y_star + S,
              Y_list ~ Y_star + X + Z,
              S ~ U,
              X ~ U,
              Y_star ~ U)

nodes <-
  tibble(
    name = c("U", "S", "Y_star", "X", "Y_direct", "Y_list", "Z"),
    label = c(
      "U",
      "S",
      "Y<sup>*</sup>",
      "X",
      "Y<sup>D</sup>",
      "Y<sup>L</sup>",
      "Z"
    ),
    annotation = c(
      "**Unknown heterogeneity**",
      "**Sensitivity bias**",
      "**Latent**<br> Sensitive trait",
      "Control item count",
      "**Outcome 1**<br> Direct question",
      "**Outcome 2**<br> List question",
      "**Random assignment**<br>List experiment condition"
    ),
    
    x = c(-75,-25,-25,-25, 25, 25, 75),
    y = c(0, 50, 0, -50, 50,-50,-50),
    text_x = x,
    nudge_y = c(18, 18, 18, 18, 18, 18, 18),
    text_y = y + nudge_y
  )

ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# audit experiment


```{r}
 
design <- 
  declare_population(N = 100,
                     U = rnorm(N)) +
  declare_potential_outcomes(R ~ if_else(Z + U > 0.5, 1, 0), conditions = list(Z = c(0, 1))) +
  declare_potential_outcomes(Q ~ if_else(R == 1, Z + U, NA_real_), conditions = list(Z = c(0, 1), R = c(0, 1))) +
  declare_estimand(ATE_R = mean(R_Z_1 - R_Z_0)) + 
  declare_estimand(CATE_ar = mean(Q_Z_1_R_1 - Q_Z_0_R_1), subset = (R_Z_1 == 1 & R_Z_0 == 0)) + 
  declare_assignment(prob = 0.5) +
  declare_reveal(R, Z) +
  declare_reveal(Q, c(Z, R)) +
  declare_estimator(R ~ Z, estimand = "ATE_R", label = "ATE_R") +
  declare_estimator(Q ~ Z, subset = (R == 1), estimand = "CATE_ar", label = "CATE_ar")

dag <- dagify(
  Q ~ R + Z + U,
  R ~ Z + U
)

nodes <-
  tibble(
    name = c("Z", "R", "Q", "U"),
    label = c("Z", "R", "Q", "U"),
    annotation = c(
      "**Random assignment**<br> Subject sent email",
      "**Outcome 1**<br>Subject replies to email",
      "**Outcome 2**<br>Email quality",
      "**Unknown heterogeneity**"),
    x = c(-0.25, 0, 0, 0.25),
    y = c(0, 0.25, -.25, 0),
    text_x = x,
    text_y = c(0+ 0.2, 0.25+ 0.2, -.25 - 0.2, 0+ 0.2)
  )

ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```

# random sampling


```{r}
 
fixed_population <- declare_population(N = 500, Y = sample(1:7, N, replace = TRUE))()

random_sampling_design <- 
  declare_population(data = fixed_population) + 
  declare_estimand(Y_bar = mean(Y)) + 
  declare_sampling(n = 100) + 
  declare_estimator(Y ~ 1, model = lm_robust, estimand = "Y_bar")

dag <- dagify(Y ~ S)
nodes <- get_design_nodes(random_sampling_design)



nodes <-
  tibble(
    name = c("Y", "S"),
    label = c("Y", "S"),
    annotation = c("**Outcome**<br>measured only for sampled units",
                   "**Sampling indicator**<br>randomly set by designer"),
    x = c(25, -25),
    y = c(0, 0),
    text_x = x,
    text_y = c(25, 25)
  )

ggdd_df <- make_ggdd_df(dag, nodes, design)

base_dag_plot %+% ggdd_df
```