# Complex designs

In the designs we presented thus far, the aim was generally to learn about the level of some variable or some particular causal effect. In most cases, a single set of observations was collected and an answer strategy was applied directly to this data to answer a pre-defined question. 

Very many studies have this form. But studies can also be "complex" in multiple ways. For instance although we have assumed researchers start with well defined estimands, some studies focus on first figuring out what question to ask and then proceed to ask and answer it. Some studies seek not to learn about levels and effects but search explicitly for a model of a phenomenon, asking for instance "what causes $Y$?" or  "what model, in some class, best accounts for observed data"? These studies have complex inquiries. Other studies have complex data and answer strategies, for instance, gathering together findings from multiple sub-studies in order to arrive at an overall conclusion.  

We address the declaration and diagnosis of such complex designs in this section. 