# Experimental designs for descriptive inference

Why would we ever need to do an *experiment* to do descriptive inference?

Suppose we want to understand the causal model $M$ of a violin. In particular, we have a descriptive inquiry $I$ about the pitch of the highest string, the E string. We want to know if the E string is in tune. Call the latent pitch of the string $Y^*$. No matter how hard we listen to the string, we can't hear $Y^*$ -- it is latent. As part of a data strategy $D$, we could measure the pitch by $P$ plucking it: $Y^* -> Y <- P$. This is descriptive research about the causal model $M$, because the DAG of the violin includes four string nodes which each cause pitch nodes; we'd like to know a descriptive fact about the pitch nodes (what frequency they are vibrating at.)

This could also be a causal inquiry: the untreated potential outcome is the pitch of the unplucked string, as defined by the frequency of vibration -- while strings are never *perfectly* still, we can call the untreated potential outcome $Y_i(0) = 0hz$. The treated potential outcome is the vibrations when the string is plucked $Y_i(1) = 650hz$. The causal effect of plucking the string is $Y_i(1) - Y_i(0) = 650 - 0 = 650$. 

This is a sense in which causal inference and descriptive inference are the same. Whether framed as a descriptive inquiry or a casual inquiry, we arrive at an answer of 650 hertz. Violinists reading this will know that that means the E string is flat and will need to be tuned up to $659.3hz$ (if using equal temperament).

