on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # run every day at 11 PM
    - cron: '0 23 * * *'

name: build-book

env:
  isExtPR: ${{ github.event.pull_request.head.repo.fork == true }}

jobs:
  build:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@master

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-6-${{ hashFiles('DESCRIPTION') }}
          restore-keys: r-6-

      - name: Install pak
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          pak::local_install_dev_deps(upgrade = TRUE)
        shell: Rscript {0}
        
      - name: Search for rmd dependences
        run: Rscript -e 'library(checkpoint); found_packages <- scanForPackages(".", use.knitr = TRUE)$pkgs; if(length(found_packages[!found_packages%in% installed.packages()]) > 0) install.packages(found_packages[!found_packages%in% installed.packages()])'

      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: _bookdown_files
          key: bookdown-2-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-2-

      - name: Prep Dropbox files
        run: |
          mkdir ~/Dropbox
          mkdir ~/Dropbox/DeclareDesign_book_rfiles
          wget -O ~/Dropbox/files.zip https://www.dropbox.com/sh/fqjlu8k90sx6kv8/AADcmSxqO35f4LEvHyJjl1Dwa?dl=1
          unzip ~/Dropbox/files.zip -d ~/Dropbox/DeclareDesign_book_rfiles -x /

      - name: Build book
        run: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::bs4_book")'

      - name: Push to gh-pages
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: '_book'
          CLEAN: true
          
          